// Generated by gencpp from file aimm_gazebo/ColorSequence.msg
// DO NOT EDIT!


#ifndef AIMM_GAZEBO_MESSAGE_COLORSEQUENCE_H
#define AIMM_GAZEBO_MESSAGE_COLORSEQUENCE_H

#include <ros/service_traits.h>


#include <aimm_gazebo/ColorSequenceRequest.h>
#include <aimm_gazebo/ColorSequenceResponse.h>


namespace aimm_gazebo
{

struct ColorSequence
{

typedef ColorSequenceRequest Request;
typedef ColorSequenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ColorSequence
} // namespace aimm_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aimm_gazebo::ColorSequence > {
  static const char* value()
  {
    return "3969b5fd7ff15f6de27340edae0cd056";
  }

  static const char* value(const ::aimm_gazebo::ColorSequence&) { return value(); }
};

template<>
struct DataType< ::aimm_gazebo::ColorSequence > {
  static const char* value()
  {
    return "aimm_gazebo/ColorSequence";
  }

  static const char* value(const ::aimm_gazebo::ColorSequence&) { return value(); }
};


// service_traits::MD5Sum< ::aimm_gazebo::ColorSequenceRequest> should match
// service_traits::MD5Sum< ::aimm_gazebo::ColorSequence >
template<>
struct MD5Sum< ::aimm_gazebo::ColorSequenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aimm_gazebo::ColorSequence >::value();
  }
  static const char* value(const ::aimm_gazebo::ColorSequenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aimm_gazebo::ColorSequenceRequest> should match
// service_traits::DataType< ::aimm_gazebo::ColorSequence >
template<>
struct DataType< ::aimm_gazebo::ColorSequenceRequest>
{
  static const char* value()
  {
    return DataType< ::aimm_gazebo::ColorSequence >::value();
  }
  static const char* value(const ::aimm_gazebo::ColorSequenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aimm_gazebo::ColorSequenceResponse> should match
// service_traits::MD5Sum< ::aimm_gazebo::ColorSequence >
template<>
struct MD5Sum< ::aimm_gazebo::ColorSequenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aimm_gazebo::ColorSequence >::value();
  }
  static const char* value(const ::aimm_gazebo::ColorSequenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aimm_gazebo::ColorSequenceResponse> should match
// service_traits::DataType< ::aimm_gazebo::ColorSequence >
template<>
struct DataType< ::aimm_gazebo::ColorSequenceResponse>
{
  static const char* value()
  {
    return DataType< ::aimm_gazebo::ColorSequence >::value();
  }
  static const char* value(const ::aimm_gazebo::ColorSequenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIMM_GAZEBO_MESSAGE_COLORSEQUENCE_H
